/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogInImport } from './routes/logIn'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LogInRoute = LogInImport.update({
  path: '/logIn',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/logIn': {
      id: '/logIn'
      path: '/logIn'
      fullPath: '/logIn'
      preLoaderRoute: typeof LogInImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, LogInRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/logIn"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/logIn": {
      "filePath": "logIn.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
